version: '3.8'

services:

  app:
    image: ayamelenevych/hospitalappointmentapi
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - appdb
    restart: unless-stopped
    env_file: ./.env
    ports: 
      - ${PORT}:${PORT}
    
  appdb:
    image: mysql:8.0
    container_name: db-1
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${appdb}
      MYSQL_USER: ${root}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "8080:8080"
    volumes:
      - ./dumps:/docker-entrypoint-dumpsdb.d
     
    command: --init-file /data/application/appdb

  
      

